# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171017_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(null=True),
        ),
    ]
