# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='vanzari',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
